apiVersion: batch/v1
kind: Job

metadata:
  name: migrator
  namespace: dev

spec:
  template:
    metadata:
      labels:
        app: migrator
    spec:
      restartPolicy: Never
      hostNetwork: true
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: migrator
        image: reg.rullabcd.my.id/library/app-migrator:7
        command: [ "sh", "-c" ]
        args: [ "npx prisma migrate deploy && npx prisma db seed" ]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: next-secrets
              key: database-url
