apiVersion: v1
kind: Secret

metadata:
  name: next-secrets
  namespace: dev

type: Opaque
stringData:
  database-url: "mysql://rullabcd:rullabcd@db-demo.cxsciarp4wxb.us-east-1.rds.amazonaws.com:3306/demo"
